#!/usr/bin/env bash
# Worktree & environment manager for parallel workers.
#
# Creates isolated git worktrees with proper environment setup
# for each worker instance.
#
# Usage:
#   worktree-manager.sh create <worker-id> <issue-number> [base-branch]
#   worktree-manager.sh destroy <worker-id> <issue-number>
#   worktree-manager.sh list
#   worktree-manager.sh setup-env <worktree-path> <worker-id> <port-offset>
#
# Environment strategy:
#   .env.shared     → symlinked into each worktree (shared secrets/config)
#   .env.local      → generated per worktree (ports, worker ID, test isolation)
#   .venv/          → created per worktree OR symlinked if deps unchanged
#   node_modules/   → created per worktree OR symlinked

set -euo pipefail

WORKTREE_ROOT=".worktrees"
BASE_PORT=8000
ENV_SHARED=".env.shared"

# ── Create worktree ─────────────────────────────────────────────────────────
cmd_create() {
    local worker_id="${1:?Usage: create <worker-id> <issue-number> [base-branch]}"
    local issue="${2:?Usage: create <worker-id> <issue-number> [base-branch]}"
    local base_branch="${3:-main}"

    local branch="feat/issue-${issue}"
    local worktree_path="${WORKTREE_ROOT}/${worker_id}-issue-${issue}"

    if [[ -d "$worktree_path" ]]; then
        echo "{\"status\": \"exists\", \"path\": \"$worktree_path\", \"branch\": \"$branch\"}"
        return 0
    fi

    mkdir -p "$WORKTREE_ROOT"

    # Create branch if it doesn't exist
    if ! git rev-parse --verify "$branch" &>/dev/null; then
        git branch "$branch" "$base_branch"
    fi

    # Create worktree
    git worktree add "$worktree_path" "$branch"

    # Setup environment
    setup_env "$worktree_path" "$worker_id" "$issue"

    echo "{\"status\": \"created\", \"path\": \"$worktree_path\", \"branch\": \"$branch\"}"
}

# ── Setup environment in worktree ───────────────────────────────────────────
setup_env() {
    local wt_path="$1"
    local worker_id="$2"
    local issue="$3"

    # Calculate unique port offset from issue number
    local port_offset=$((issue % 100))
    local port=$((BASE_PORT + port_offset))

    # ── Shared env (symlink) ──
    if [[ -f "$ENV_SHARED" ]]; then
        ln -sf "$(pwd)/$ENV_SHARED" "$wt_path/.env.shared"
    fi

    # ── Local env (generated) ──
    cat > "$wt_path/.env.local" <<ENVEOF
# Auto-generated by worktree-manager for $worker_id
# Issue: #$issue | Worktree: $wt_path

WORKER_ID=$worker_id
OCTOBOTS_ID=$worker_id
PORT=$port
TEST_PORT=$((port + 1000))

# Isolated test database schema (prevents cross-worker test pollution)
TEST_DB_SCHEMA=test_${worker_id//[-.]/_}_${issue}

# Worker identification for logging
WORKER_LABEL="[$worker_id #$issue]"
ENVEOF

    # ── Merged .env (shared + local) ──
    {
        echo "# Merged env — auto-generated, do not edit"
        echo "# Source: .env.shared + .env.local"
        echo ""
        [[ -f "$wt_path/.env.shared" ]] && cat "$wt_path/.env.shared"
        echo ""
        cat "$wt_path/.env.local"
    } > "$wt_path/.env"

    # ── Python venv ──
    if [[ -f "$wt_path/pyproject.toml" ]] || [[ -f "$wt_path/requirements.txt" ]]; then
        if [[ -d ".venv" ]] && ! git diff --quiet "$wt_path/pyproject.toml" 2>/dev/null; then
            # Deps might differ — create fresh venv
            echo "Creating Python venv for $worker_id..."
            python3 -m venv "$wt_path/.venv"
            if [[ -f "$wt_path/pyproject.toml" ]]; then
                "$wt_path/.venv/bin/pip" install -e "$wt_path" -q 2>/dev/null || true
            elif [[ -f "$wt_path/requirements.txt" ]]; then
                "$wt_path/.venv/bin/pip" install -r "$wt_path/requirements.txt" -q 2>/dev/null || true
            fi
        elif [[ -d ".venv" ]]; then
            # Same deps — symlink for speed
            ln -sf "$(pwd)/.venv" "$wt_path/.venv"
        fi
    fi

    # ── Node modules ──
    if [[ -f "$wt_path/package.json" ]]; then
        if [[ -d "node_modules" ]] && [[ -f "package-lock.json" ]]; then
            # Check if lockfile matches
            if cmp -s "package-lock.json" "$wt_path/package-lock.json" 2>/dev/null; then
                # Same deps — symlink
                ln -sf "$(pwd)/node_modules" "$wt_path/node_modules"
            else
                # Different — install fresh
                echo "Installing node_modules for $worker_id..."
                (cd "$wt_path" && npm install --silent 2>/dev/null) || true
            fi
        fi
    fi

    # ── MCP config (symlink from project root) ──
    if [[ -f ".mcp.json" ]]; then
        ln -sf "$(pwd)/.mcp.json" "$wt_path/.mcp.json"
    fi

    # ── .env.octobots (symlink from project root) ──
    if [[ -f ".env.octobots" ]]; then
        ln -sf "$(pwd)/.env.octobots" "$wt_path/.env.octobots"
    fi

    echo "Environment ready: port=$port, test_schema=test_${worker_id//[-.]/_}_${issue}"
}

# ── Destroy worktree ────────────────────────────────────────────────────────
cmd_destroy() {
    local worker_id="${1:?Usage: destroy <worker-id> <issue-number>}"
    local issue="${2:?Usage: destroy <worker-id> <issue-number>}"

    local worktree_path="${WORKTREE_ROOT}/${worker_id}-issue-${issue}"

    if [[ ! -d "$worktree_path" ]]; then
        echo "{\"status\": \"not_found\", \"path\": \"$worktree_path\"}"
        return 0
    fi

    # Remove worktree (git handles cleanup)
    git worktree remove "$worktree_path" --force 2>/dev/null || {
        # If git worktree remove fails, manual cleanup
        rm -rf "$worktree_path"
        git worktree prune
    }

    echo "{\"status\": \"destroyed\", \"path\": \"$worktree_path\"}"
}

# ── List worktrees ──────────────────────────────────────────────────────────
cmd_list() {
    echo "Active worktrees:"
    git worktree list --porcelain | while IFS= read -r line; do
        case "$line" in
            worktree\ *)
                path="${line#worktree }"
                ;;
            branch\ *)
                branch="${line#branch refs/heads/}"
                # Only show our managed worktrees
                if [[ "$path" == *"$WORKTREE_ROOT"* ]]; then
                    local port=""
                    if [[ -f "$path/.env.local" ]]; then
                        port=$(grep "^PORT=" "$path/.env.local" 2>/dev/null | cut -d= -f2)
                    fi
                    echo "  $path  branch=$branch  port=${port:-?}"
                fi
                ;;
        esac
    done
}

# ── Main ────────────────────────────────────────────────────────────────────
case "${1:-help}" in
    create)   shift; cmd_create "$@" ;;
    destroy)  shift; cmd_destroy "$@" ;;
    list)     cmd_list ;;
    setup-env) shift; setup_env "$@" ;;
    *)
        echo "Usage: worktree-manager.sh <create|destroy|list> [args]"
        echo ""
        echo "  create  <worker-id> <issue> [base]  Create worktree + env"
        echo "  destroy <worker-id> <issue>          Remove worktree"
        echo "  list                                  Show active worktrees"
        ;;
esac
